### ISSUE TITLE
Token logger don’t run 

### ISSUE THREAD

**Issue by Aspect2222** [YaboiiPY/tiktok-view-bot#1]
PyPi received the information and will takedown the import shortly.
Stop token logging.

**Comment by YaboiiPY** [comment]
i will never stop ;)

**Comment by Aspect2222** [comment]
> i will never stop ;)

man why you don’t have anything else to do?

**Comment by YaboiiPY** [comment]
> > i will never stop ;)
> 
> man why you don’t have anything else to do?

gegenfrage hast du nichts anderes zutun als imports zu reporten? ich brauche vllt 2min dann hab ich ein neues hochgeladen haha
